# Page settings

baseurl = "https://mvaude.github.io/resume/"
languageCode = "en-us"
title = "Maxime Vaude CV"
theme = "orbit"
googleAnalytics = "UA-120354426-2"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Resume"
    author = "Maxime Vaude"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Maxime Vaude"
        tagline = "Software Developer"
        avatar = "profile.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:maxime.vaude@gmail.com"
        title = "maxime.vaude@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+33699273317"
        title = "+33 (0)6 99 27 33 17"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//mvaude.github.io"
        title = "mvaude.github.io"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/maxime-vaude-8b22465a"
        title = "linkedin.com/in/maximevaude"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/mvaude"
        title = "github.com/mvaude"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/wefirm"
        title = "@wefirm"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        college = "EPITECH"
        dates = "2010 - 2011"

        [[params.education.list]]
        degree = "Programme Grandes Ecoles de Commerce"
        college = "IDRAC Business School"
        dates = "2011 - 2013"

        [[params.education.list]]
        degree = "Introduction to Statistics: Descriptive Statistics"
        college = "BerkeleyX"
        dates = "2013"

        [[params.education.list]]
        degree = "Introduction to Computer Science and Programming Using Python"
        college = "MITx"
        dates = "2014"

        [[params.education.list]]
        degree = "Introduction to Linux"
        college = "LinuxFoundationX"
        dates = "2014"

        [[params.education.list]]
        degree = "Certificat en Technologie Numérique"
        college = "42"
        dates = "2014 - 2018"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "French"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

        [[params.language.list]]
        language = "Spanish"
        level = "Scholar"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Cinema"

        [[params.interests.list]]
        interest = "Video Games"

        [[params.interests.list]]
        interest = "Traveling"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """
##### Motivations:
- Satisfaction of my clients.
- Taste for challenges, diversity in search of perfection.
- Desire for interaction and human contact.
- Search for constant evolution.
- Adaptability and optimization of work methodologies according to missions and teams.
- Autonomy in the choice of technologies by targeting innovation and efficiency.

##### Areas of Expertise:
- Flexibility and responsiveness to address to fluctuations in an activity.
- Develop data analysis tools.
- Design solutions based on cloud or hybrid architecture.
- Develop Release and Quality Assurance solutions and methodologies for Continuous Integration and Continuous Delivery.
- Bring an outside look and put new ideas in the service of a win / win relationship.

##### Challenges:
- Implement cyber security solutions in the company calling on me and raise awareness / educate its various stakeholders.
- Develop Artificial Intelligences to improve human relations and optimize certain interactions.
- Design financial optimization solutions.
"""

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Release Engineer"
        dates = "2015 - 2016"
        company = "Scality, Paris"
        details = """
- migrate from svn to git.
- define different test pipelines (development and release).
- implement a Jenkins CI with a cloud infrastructure (Rackspace) using IaC (Infrastructure as Code).
- set up Buildbot CI with docker workers for the static test checkers, linters, unit tests suites, due to load problems with Jenkins (with 160 parallel builds).
- Develop engineering KPIs, compute them and display them on dashboards in offices.
- Define Release and Contribution processes based on agile methodologies (mainly SCRUM and KANBAN).
- develop a tool to aggregate Open-Source licenses for software and system dependencies.
- develop a git merging robot. It includes pipelines and tells developers and reviewers where a merge block comes from and what are the missing steps to integrate the branch (ticket definition, test failure).
""" 

        [[params.jobs.list]]
        position = "QA Developer"
        dates = "2016"
        company = "Scality, Paris"
        details = """
- develop series of integration tests for the product's web interface (pytest, docker, selenium) with automated build in the CI.
"""

        [[params.jobs.list]]
        position = "R&D Engineer"
        dates = "2016 - 2017"
        company = "Scality, Paris"
        details = """
- develop a tool to dynamically patch the Node.js private dependencies (for example for end-to-end testing of a specific development branch on each dependency).
- set up the CI (Circle CI / AWS) with definition of the different pipelines.
- deploy serverless micro-services to manage resources and costs in the cloud (AWS) with Terraform (cloud resources watchers and killers using AWS CloudWatch, Lambda, SQS, EC2, S3).
- make the Scality S3 connector's installer compatible with offline installations.
- develop tools for a detailed report on the cost and use of resources in the cloud by each member or team of the organization.
- monitor the Github activities of the organization (TICK Stack with Influx DB).
"""

    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"


    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Python"
        level = "90%"

        [[params.skills.list]]
        skill = "Shell"
        level = "85%"

        [[params.skills.list]]
        skill = "Golang"
        level = "80%"

        [[params.skills.list]]
        skill = "Javascript"
        level = "70%"

        [[params.skills.list]]
        skill = "C"
        level = "40%"

        [[params.skills.list]]
        skill = "Rust"
        level = "20%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Maxime Vaude"
