# Page settings

baseurl = "https://thithuha.github.io/resume/"
languageCode = "en-us"
title = "Thi Thu Ha CV"
theme = "orbit"
googleAnalytics = "UA-120354426-2"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

# Default language is English
DefaultContentLanguage = "en"

[params]

# Meta
    description = "Resume"
    author = "Thi Thu Ha Nguyen"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Thi Thu Ha Nguyen"
        tagline = "Product Owner"
        avatar = "profile.jpg"

    # Avaibility
    [params.available]
        enable = false
        title = "Unavailable"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:thithuha.nguyen94@gmail.com"
        title = "thithuha.nguyen94@gmail.com"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//thithuha.github.io/resume"
        title = "thithuha.github.io/resume"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/thithuha"
        title = "linkedin.com/in/thithuha"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/Thithuha"
        title = "github.com/Thithuha"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Full Stack Web Developer"
        college = "Le Wagon"
        dates = "2021"

        [[params.education.list]]
        degree = "Management du luxe"
        college = "LVMH - La Samaritaine"
        dates = "2020"

        [[params.education.list]]
        degree = "Chef de Projet Multimédia"
        college = "IESA Institut d'études supérieures des arts"
        dates = "2015 - 2018"

        [[params.education.list]]
        degree = "UTS Foundation Studies - Arts and Social Sciences"
        college = "UTS University of Technology Sydney"
        dates = "2012 - 2014"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Vietnamese"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

        [[params.language.list]]
        language = "French"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Art"

        [[params.interests.list]]
        interest = "Cinema"

        [[params.interests.list]]
        interest = "Traveling"

        [[params.interests.list]]
        interest = "Gastronomy"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """
##### Motivations:
- Serve as the voice of the product.
- Act as an ambassador for the product internally and externally and as the primary contact for queries related to the product.
- Define product vision, road-map and growth opportunities.
- Desire for interaction and human contact.

##### Areas of Expertise:
- The experience in sales and marketing.
- Experience with software development, including knowledge of coding languages.
- Outlining the customer journey and mocking up product designs to mapping product dependencies.
- Ability to work with cross-functional teams to deliver on a common goal.


##### Challenges:
- Solve product-related problems, complete trade-off analysis to stay on track towards business deliverable commitments.
- Evaluating product progress at each iteration.
- Maximizing the value of the product resulting from the work of the development team.
"""

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Sale Advisor"
        dates = "2022"
        company = "Isabel Marant, Paris"
        details = """
- Build genuine relationships with clients through thoughtful and consistent outreach.
- Maintain an excellent level of customer service.
- Assist with the sales process by maintaining a fully stocked store.
"""


        [[params.jobs.list]]
        position = "Sale Advisor"
        dates = "2021"
        company = "APM Monaco, Lyon"
        details = """
- Act as an ambassador for the Brand at all times.
- Drive store business and grow the client base.
- Provide details on return policies and handling procedures.
"""

        [[params.jobs.list]]
        position = "Sale Advisor"
        dates = "2019 - 2020"
        company = "Balmain, Paris"
        details = """
- Meet and exceed sales goals.
- Operate cash registers and close daily revenues.
- Manage the merchandise promptly according to the demand.
"""

        [[params.jobs.list]]
        position = "Web Marketer and Designer"
        dates = "2018 - 2019"
        company = "Acanthe paris, Paris"
        details = """
- Creating marketing materials such as brochures, flyers, and catalogs for print advertising campaign.
- Developing and executing marketing campaigns using newsletter.
- Incorporating brand elements and relevant market research findings into website.
- Implementing strategies for improving conversion rates and generating leads from website visitors.
"""

        [[params.jobs.list]]
        position = "Web Designer"
        dates = "2017"
        company = "Bazarchic, Paris"
        details = """
- Designing engaging and responsive landing pages.
- Integrating client CMS programs and data feeds into websites.
- Optimising visual features for maximum speed and scalability.
- Ensuring website function and stability across devices i.e. desktop, mobile, tablet.
"""

        [[params.jobs.list]]
        position = "Graphiste - Web Designer"
        dates = "2016"
        company = "Wall Market, Paris"
        details = """
- Conceptualizing creative ideas of product.
- Establishing design guidelines, standards, and best practices.
- Designing visual imagery for websites and ensuring that they are in line with branding for clients.
- Liaising with back-end developers to ensure web and app logic is properly integrated.
"""





    # Hackathons section
    [params.hackathons]
        enable = true
        icon = "fa-trophy"
        title = "Hackathons"


        [[params.hacks.list]]
            theme = "Culture Experience Days - no contest"
	    url = "https://www.adami.fr/evenements/culture-experience-days/"
            dates = "2015"
            organisator = "Adami, Paris"
            details = "The purpose were to offer, thanks to the technology, a different experience between an artist and his public. We decided to take the use case of an improvisator: we developed a connected t-shirt reflecting twitter votes from the public through different blinkings colors LED."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Software Development"
        level = "60%"

        [[params.skills.list]]
        skill = "Web Development"
        level = "70%"

        [[params.skills.list]]
        skill = "UX/UI Design"
        level = "90%"

        [[params.skills.list]]
        skill = "Web Design"
        level = "90%"

        [[params.skills.list]]
        skill = "Agile Methodologies"
        level = "40%"

        [[params.skills.list]]
        skill = "User Stories Definition"
        level = "50%"

    # Footer section

    [params.footer]
        copyright = "Thi Thu Ha Nguyen"


## French traduction section

[languages]
    [languages.en]
        languageName = "English"
        weight = 1
    [languages.fr]
        languageCode = "fr-fr"
        languageName = "French"
        weight = 2

        # Avaibility
        [languages.fr.params.available]
            enable = false
            title = "Indisponible"
        [languages.fr.params.summary]
            enable = true
            icon = "fa-user"
            title = "Profil"
            summary = """
##### Motivations:
- Etre de porte-parole du produit
- Agir en tant qu'ambassadeur du produit à l'interne et à l'externe et en tant que contact principal pour les queries liées au produit.
- Définir la vision du produit, le road-map et les opportunités de croissance.
- Goût de l'échange et du contact humain.

##### Domaines d'Expertise:
- L'expérience dans la vente et le marketing.
- Expérience en développement de logiciels, y compris connaissance des langages de codage.
- Décrire le parcours client et modéliser les conceptions de produits pour cartographier les dépendances des produits.
- Capacité à travailler avec des équipes interfonctionnelles pour atteindre un objectif commun.

##### Ambitions/Défis:
- Résolvez les problèmes liés aux produits, complétez l'analyse des compromis pour rester sur la bonne voie par rapport aux engagements livrables de l'entreprise.
- Évaluer la progression du produit à chaque itération.
- Maximiser la valeur du produit résultant du travail de l'équipe de développement.

"""

        # Experiences section
        [languages.fr.params.experiences]
            enable = true
            icon = "fa-briefcase"
            title = "Expériences"

        [[languages.fr.params.jobs.list]]
        position = "Sale Advisor"
        dates = "2022"
        company = "Isabel Marant, Paris"
        details = """
- Relation et suivi clients.
- Proposer un service complémentaire à la vente.
- Gestion des stocks et des approvisionnements.
"""

        [[languages.fr.params.jobs.list]]
        position = "Sale Advisor"
        dates = "2021"
        company = "APM Monaco, Lyon"
        details = """
- Agir à tout moment comme ambassadeur de la Marque
- Stimuler l'activité du magasin et développer la clientèle.
- Assurer un service après-vente.
"""

        [[languages.fr.params.jobs.list]]
        position = "Sale Advisor"
        dates = "2019 - 2020"
        company = "Balmain, Paris"
        details = """
- Vente et developpement commercial avec objectif.
- Gestion de la caisse.
- Réassort de l’espace de vente et du Merchandising.
"""

        [[languages.fr.params.jobs.list]]
        position = "Web Marketer and Designer"
        dates = "2018 - 2019"
        company = "Acanthe paris, Paris"
        details = """
- Création de supports marketing tels que brochures, dépliants et catalogues pour la campagne publicitaire imprimée.
- Élaboration et exécution de campagnes marketing à l'aide de la newsletter.
- Incorporer des éléments de marque et des résultats d'études de marché pertinents sur le site Web.
- Mettre en œuvre des stratégies pour améliorer les taux de conversion et générer des prospects auprès des visiteurs du site Web.
"""

        [[languages.fr.params.jobs.list]]
        position = "Web Designer"
        dates = "2017"
        company = "Bazarchic, Paris"
        details = """
- Réaliser le design d'un site web responsive.
- Intégration des programmes CMS clients et des flux de données dans les sites Web.
- Optimisation des fonctionnalités visuelles pour une vitesse et une évolutivité maximales.
- Assurer le fonctionnement et la stabilité du site Web sur tous les appareils, ordinateur, mobile, tablette.
"""

        [[languages.fr.params.jobs.list]]
        position = "Graphiste - Web Designer"
        dates = "2016"
        company = "Wall Market, Paris"
        details = """
- Définir le concept, la thématique d'un produit.
- Opérer des choix techniques, esthétiques, économiques pour un produit.
- Concevoir des images visuelles pour les sites Web et s'assurer qu'elles sont conformes à l'image de marque des clients.
- Assurer la liaison avec les développeurs back-end pour s'assurer que la logique Web et d'application est correctement intégrée.
"""


        # Hackathons section
        [languages.fr.params.hackathons]
            enable = true
            icon = "fa-trophy"
            title = "Hackathons"


            [[languages.fr.params.hacks.list]]
                theme = "Culture Experience Days - pas de compétition"
	            url = "https://www.adami.fr/evenements/culture-experience-days/"
                dates = "2015"
                organisator = "Adami, Paris"
                details = "Le but était d'offrir, grâce à la technologie, une expérience différente entre un artiste et son public. Nous avons décidé de prendre le cas d'un improvisateur: nous avons développé un t-shirt connecté reflétant les votes Twitter du public à travers différentes couleurs clignotantes LED."


        # Languages section
        [languages.fr.params.language]
            enable = true
            title = "Langues"

            [[languages.fr.params.language.list]]
            language = "Français"
            level = "Professionnel"

            [[languages.fr.params.language.list]]
            language = "Anglais"
            level = "Professionnel"

            [[languages.fr.params.language.list]]
            language = "Vietnamien"
            level = "Maternelle"

        # Interests section
        [languages.fr.params.interests]
            enable = true
            title = "Intérêts"

            [[languages.fr.params.interests.list]]
            interest = "Art"

            [[languages.fr.params.interests.list]]
            interest = "Cinéma"

            [[languages.fr.params.interests.list]]
            interest = "Voyages"

            [[languages.fr.params.interests.list]]
            interest = "Gastronomie"

        # Skills section
        [languages.fr.params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Compétences Informatiques"

            [[languages.fr.params.skills.list]]
            skill = "Software Development"
            level = "60%"

            [[languages.fr.params.skills.list]]
            skill = "Web Development"
            level = "70%"

            [[languages.fr.params.skills.list]]
            skill = "UX/UI Design"
            level = "90%"

            [[languages.fr.params.skills.list]]
            skill = "Web Design"
            level = "90%"

            [[languages.fr.params.skills.list]]
            skill = "Agile Methodologies"
            level = "40%"

            [[languages.fr.params.skills.list]]
            skill = "User Stories Definition"
            level = "50%"

        # Profile section
        [languages.fr.params.profile]
            name = "Thi Thu Ha Nguyen"
            tagline = "Product Owner"
            avatar = "profile.jpg"
